version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u212-jdk-stretch
    steps:
      - checkout
      - run: bash ./echo.sh
workflows:
  version: 2
  default:
    jobs:
      - build
